name: Bug Report
description: Report a bug in the Decky plugin
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! If this affects the CapyDeploy Hub or Desktop Agent, please report it in the [main project](https://github.com/lobinuxsoft/capydeploy/issues) instead.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Enable plugin in Decky
        2. Connect from Hub
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - Device: [e.g., Steam Deck LCD, Steam Deck OLED, OneXFly]
        - OS: [e.g., SteamOS 3.5, Bazzite 40]
        - Decky Loader version: [e.g., 2.12.0]
        - Plugin version: [e.g., 0.4.0]
        - Hub version: [e.g., 0.4.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Check ~/homebrew/logs/CapyDeploy/ for plugin logs
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Want to contribute a fix?** Great! Please:
        1. Wait for the issue to be triaged
        2. Create a branch: `fix/issue-XX-short-description`
        3. Submit a PR targeting `main`

        See [CONTRIBUTING.md](https://github.com/lobinuxsoft/decky-capydeploy/blob/main/CONTRIBUTING.md) for details.
